# Generated by Django 4.0.4 on 2022-06-04 13:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
